version: '3'
services:
  larch-core:
    build: './larch-core'
    links:
      - db
    ports:
      - '8055:8055'
  larch-front:
    build: './larch-front'
    links:
      - larch-core
    ports:
      - '3000:3000'
  db:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: secret